### ISSUE TITLE
"Explosive" Trait Bug

### ISSUE THREAD

**Issue by scooterwolfie** [Flo56958/MineTinker#259] opened 2023-12-29 06:00 UTC
Basically what happens is when I have an Explosive trait on a sword and try to kill things, about 10% of the time the mobs will go to 1hp and become immortal.

![image](https://github.com/Flo56958/MineTinker/assets/149985472/c0a90d91-8ebf-4ad9-8359-7d0f4894fdcf)

![image](https://github.com/Flo56958/MineTinker/assets/149985472/fe44a13a-cf7f-404a-a640-f04e36f79406)

**Comment by Flo56958** [comment] 2023-12-29 09:18
So i tested it on my end but i cannot replicate the problem. It could be something with the other plugins you have installed. mcMMO had some incompatibilities. You can try to enable the pattern matcher in layout.yml.

**Comment by Flo56958** [comment] 2024-01-12 22:30
@scooterwolfie i will close the issue, but feel free to reopen it (and the other one) if the issue is from MineTinker

**Closed by Flo56958** 2024-01-12 22:30 UTC
Labels: bug
