### ISSUE TITLE
[Bug] Bottles O'Enchanting not working.

### ISSUE THREAD

**Issue by FatalBlade** [Flo56958/MineTinker#88] opened 2019-06-30 03:37 UTC
**Describe the bug**
bottles of experience will only drop xp if there is only one in hand.

**To Reproduce**
1. grab a stack of experience bottles
2. try to use them with a right click
3. bottle is used however no experience is dropped
4. exp will not drop until there is only one left

**Expected behavior**
experience to drop as each individual bottle is broken

**Information about the server (please complete the following information):**
 - Cannot find the version number however it's the latest release as of this posting on spigot
 - 1.14.2 spigot
 - **I reproduced this problem after removing all other plugins** however here is the list of others that are on my server:  https://pastebin.com/QHEsXW0j

**Additional context**.
Config.yml: https://pastebin.com/miFGd1VG
There are no errors thrown to the console.

**Comment by Draycia** [comment] 2019-06-30 03:41
This should be fixed in one of the indev changes.
I'll double check if it is when I can soon.

**Comment by FatalBlade** [comment] 2019-06-30 03:45
Awesome, thank you for the quick response!

**Comment by Draycia** [comment] 2019-06-30 04:04
Yeah this seems to be one of the fixes, I can't reproduce it with the latest changes. Will be in the next release, whenever that may be.

**Closed** 2019-06-30 04:06 UTC
Labels: bug
